---
- name: Testing andrewrothstein.istio
  hosts: all
  tasks:
    - name: Installing andrewrothstein.istio
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'istioctl version --remote=false'
      ansible.builtin.command: /usr/local/bin/istioctl version --remote=false
      changed_when: false
      register: istio_test_output
    - name: Output from 'istioctl version --remote=false'
      ansible.builtin.debug:
        msg: '{{ istio_test_output.stdout }}'
